create table if not exists game_question (
    id bigint generated by default as identity primary key not null,
    game_id UUID not null,
    question_id UUID not null,

    constraint unique_game_question_pair unique (game_id, question_id),
    foreign key (game_id) references game (id),
    foreign key (question_id) references question (id)
)