create table if not exists player_session_item (
    id bigint generated by default as identity primary key not null,
    session_id bigint not null,
    question_id UUID not null,

    answers jsonb default null,
    is_correct boolean default null,
    answered_at TIMESTAMPTZ default null,

    created_at TIMESTAMPTZ not null default NOW(),
    updated_at TIMESTAMPTZ not null default NOW(),

    foreign key (session_id) references player_session (id),
    foreign key (question_id) references question (id)
)