create table if not exists game_settings (
    id bigint generated by default as identity primary key not null,
    game_id UUID not null,

    is_private boolean not null default false,
    shuffle_questions boolean not null default false,
    shuffle_answers boolean not null default false,

    foreign key (game_id) references game (id),
    constraint unique_game_id unique (game_id)
)