// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package frontend_components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Redirect(targetUrl string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Redirect_f4e1`,
		Function: `function __templ_Redirect_f4e1(targetUrl){window.location = targetUrl
}`,
		Call:       templ.SafeScript(`__templ_Redirect_f4e1`, targetUrl),
		CallInline: templ.SafeScriptInline(`__templ_Redirect_f4e1`, targetUrl),
	}
}
