// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package frontend_components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func GlobalMessages() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"global-messages\" class=\"toast\"></div><script type=\"text/javascript\">\n        htmx.on(\"htmx:responseError\", function (evt) {\n           addMessage(evt.detail.xhr.responseText, 'error')\n        })\n\n        function addMessage(message, messageType) {\n            let globalMessages = document.getElementById(\"global-messages\")\n            globalMessages.innerHTML += `\n                    <div class=\"alert alert-`+ messageType +`\">\n                        <span>`+ message +`</span>\n                        <button class=\"btn btn-ghost btn-xs btn-square\" onclick=\"closeMessage(this)\">\n                            <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"1.5\" stroke=\"currentColor\" class=\"size-6\">\n                              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M6 18 18 6M6 6l12 12\" />\n                            </svg>\n                        </button>\n                    </div>`\n        }\n\n        function closeMessage(el) {\n            el.parentElement.remove()\n        }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
