name: build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  CR_URI: quiz-whiz.cr.cloud.ru


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}

      - name: Go - Build and push docker image to Evolution Aritfact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/evo-restapigo:${{ github.sha }}
          file: ./Dockerfile
          context: .
  migrations:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply migrations
        uses: ./.github/actions/db_migrations
        with:
          db-connection: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
          source: file://db/migrations
  deploy:
    needs: [build, migrations]
    runs-on: ubuntu-latest
    steps:
     - name: Deploy Stage
       uses: fjogeleit/http-request-action@v1
       with:
        url: ${{ secrets.COOLIFY_URL }}/api/v1/deploy?uuid=${{ secrets.COOLIFY_APP_ID }}&force=false
        method: 'GET'
        bearerToken: ${{ secrets.COOLIFY_TOKEN }}
